name: sofp
version: '0.0.1'
summary: A (S)tack (O)ver(f)low (P)arser
description: SOFP downloads and parses the archives hosted at https://archive.org/details/stackexchange.
grade: stable
confinement: strict
base: core


apps:
  sofp:
    command: bin/wrapper
    daemon: simple
    plugs: [network, removable-media]
  rsync:
    command: bin/rsync  --config=$SNAP_DATA/rsync.conf --daemon --no-detach
    daemon: simple
    plugs: [network, network-bind]
  

parts:
  sofp:
    source: .
    plugin: go
    go-packages: ["github.com/ryanjyoder/sofp/cmd/downloader"]
    stage-packages:
      - p7zip-full
    build-packages:
      - git
    override-build: |
      export GO111MODULE=on
      echo _______________________ Building Binary _______________________________
      go build cmd/downloader/downloader.go
      echo _______________________ Build finished ________________________________
      mkdir  -p $SNAPCRAFT_PART_INSTALL/bin
      cp downloader $SNAPCRAFT_PART_INSTALL/bin/
      cp bin/wrapper $SNAPCRAFT_PART_INSTALL/bin/
      cp bin/7z $SNAPCRAFT_PART_INSTALL/bin/
      cp rsync.conf $SNAPCRAFT_PART_INSTALL
      cp clientserver.c.patch $SNAPCRAFT_STAGE
      echo _______________________ Building finsihed ___________________________

  
  rsync:
    source: https://download.samba.org/pub/rsync/src/rsync-3.1.3.tar.gz
    plugin: autotools
    override-build: |
      patch clientserver.c < $SNAPCRAFT_STAGE/clientserver.c.patch
      snapcraftctl build
    after: [sofp]
      
