name: sofp
version: '0.0.1'
summary: A (S)tack (O)ver(f)low (P)arser
description: SOFP downloads and parses the archives hosted at https://archive.org/details/stackexchange.
grade: stable
confinement: strict
base: core


apps:
  sofp:
    command: bin/wrapper
    daemon: simple
    plugs: [network, removable-media]
  rsync:
    command: usr/bin/rsync  --config=$SNAP/rsync.conf --daemon --no-detach
    daemon: simple
    plugs: [network]
  

parts:
  sofp:
    source: .
    plugin: go
    go-packages: ["github.com/ryanjyoder/sofp/cmd/downloader"]
    stage-packages:
      - p7zip-full
      - rsync
    build-packages:
      - git
    override-build: |
      export GO111MODULE=on
      echo _______________________ Building Binary _______________________________
      go build cmd/downloader/downloader.go
      echo _______________________ Build finished ________________________________
      mkdir  -p $SNAPCRAFT_PART_INSTALL/bin
      cp downloader $SNAPCRAFT_PART_INSTALL/bin/
      cp bin/wrapper $SNAPCRAFT_PART_INSTALL/bin/
      cp bin/7z $SNAPCRAFT_PART_INSTALL/bin/
      cp rsync.conf $SNAPCRAFT_PART_INSTALL
      echo _______________________ Building finsihed ___________________________
  

      
